### PR TITLE
egl device index

### PR DESCRIPTION
**Pull request by christopher-hesse**

### CODE REVIEW

**Comment by einarf** [comment]
Works great here in an Ubuntu 19.10 VM. I might have to query for EGL version + adding fallback.
Still, this is a step in the right direction.

**Comment by einarf** [comment]
Need to do a bit more testing + fallabck+ add info in readme and this is good to do. If I somehow forget, please poke me.

**Comment by christopher-hesse** [comment]
Fallback to `EGL_DEFAULT_DISPLAY`?  Seems fine though I left it out to because it would complicate the logic.  Do any supported platforms rely on that?

**Comment by einarf** [comment]
Yup. Fallback to `EGL_DEFAULT_DISPLAY` is what I'm thinking as well. Time will show when doing real testing.

**Comment by christopher-hesse** [comment]
Any idea when the next version of glcontext will be released?  It's annoying to depend on the git version.

**Comment by einarf** [comment]
I got a bit busy on moderngl 5.6.1 work. I've released `2.3.dev0` now with your changes.

**Comment by christopher-hesse** [comment]
Thanks!

**Pull request merged**
